# Generated by Django 2.1.3 on 2019-01-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PTTPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('push', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('times', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
