# Generated by Django 2.1.3 on 2019-01-30 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_pttlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pttlink',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 10, 45, 25, 258570, tzinfo=utc)),
        ),
    ]
