# Generated by Django 2.1.3 on 2019-01-30 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20190130_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pttlink',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterField(
            model_name='pttlink',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 12, 55, 52, 326704, tzinfo=utc)),
        ),
    ]
